### ISSUE TITLE
Misplaced ) brace in defines

### ISSUE THREAD

**Issue by salkinium** [STMicroelectronics/STM32CubeF2#1]
**Describe the set-up**
 * arm-none-eabi-gcc
 * `#include <stm32f2xx.h>`

**Describe the bug**

The `SYSCFG_EXTICR1_EXTI*` defines sometimes contain a trailing `)`.
```c
#define SYSCFG_EXTICR3_EXTI9_PF         0x00000050)                            /*!<PF[9] pin */
```

**How To Reproduce**
Try to use `SYSCFG_EXTICR3_EXTI9_PF` without causing a syntax error.

**Additional context**

These are **a lot** of mistakes, so see [the full patch](https://github.com/modm-io/cmsis-header-stm32/blob/master/patches/f2.patch).

**Comment by CCASTM** [comment]
Hello Salkinium,
Thank you for your finding, we have missed this syntax errors.
The correction is obvious, you can update on your side
We will provide the updated code in our next publication @KORKAD
Regards
Christophe

**Comment by CCASTM** [comment]
ST Internal Reference: 67748

**Comment by CCASTM** [comment]
adding Ali in the thread @ALABSTM

**Comment by ALABSTM** [comment]
Hi Salkinium,

Thank you once more for your contribution. Actually we already identified this issue and corrected it. It will be available in our next release, i.e. v1.8.0.

With regards
