### ISSUE TITLE
Missing return at end of a non void function

### ISSUE THREAD

**Issue by RetoFx** [STMicroelectronics/STM32CubeF2#12]
Hi
In File stm32f2xx_hal_nand.c at the end of the following functions
HAL_StatusTypeDef HAL_NAND_RegisterCallback()
and
HAL_StatusTypeDef HAL_NAND_UnRegisterCallback()
is no 
return status;
Please fix this

**Comment by ASEHSTM** [comment]
ST Internal Reference: 149810

**Comment by KRASTM** [comment]
Fixed in [bc39f12](https://github.com/STMicroelectronics/stm32f2xx_hal_driver/commit/bc39f126b391794f2fb0ef01ebd7e3368a71843e)
