### ISSUE TITLE
const

### ISSUE THREAD

**Issue by RetoFx** [STMicroelectronics/STM32CubeF2#16]
You  add more and more const to your cube code.
This is great. const is one of the most important keywords in C.

For example

HAL_StatusTypeDef     HAL_DCMI_ConfigSyncUnmask(DCMI_HandleTypeDef *hdcmi, **const** DCMI_SyncUnmaskTypeDef *SyncUnmask);

But you add const before the type.
We and lot of other developer prefer, that const is after the type. 
This simplify the code understanding as soon as there is also a pointer.

the explanation is:

 It helps me keep track of 'what' is constant by reading the type declaration from right to left:

```
Type * const obj;        // read right-to-left:  const pointer to Object
Type const * obj;        // read right-to-left:  pointer to const Object
Type const * const obj;  // read right-to-left:  const pointer to const Object

```

So please improve this asap

**Comment by ALABSTM** [comment]
Hi @RetoFx,

Thank you for the suggestion. However, as both notations, `const Type * obj` and `Type const * obj`, are the same, we prefer keeping the first one. Thank you again for your suggestion.

With regards,
