### ISSUE TITLE
Bug in HAL_IWDG_DEFAULT_TIMEOUT

### ISSUE THREAD

**Issue by Kira-sempai** [STMicroelectronics/STM32CubeF2#4]
https://github.com/STMicroelectronics/STM32CubeF2/blob/cfa4386ba4eaae35dea33e09bac39b87480345ad/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_iwdg.c#L124

Probably should be
#define HAL_IWDG_DEFAULT_TIMEOUT        (((6UL * 256UL * 1000UL) / LSI_VALUE) + ((LSI_STARTUP_TIMEOUT / 1000UL) + 1UL))

**Comment by Kira-sempai** [comment]
BTW, can't find it's definition in stm32f2xx_hal_conf_template.h

**Comment by RKOUSTM** [comment]
Hi @Kira-sempai,

Thank you for this report.  It has been transferred to our development teams. We will be back to you as soon as we get an answer.

With regards,

**Comment by RKOUSTM** [comment]
Hi @Kira-sempai,

Thank you for your contribution. The point you reported is related to a typo in the comment description. Indeed, a fix in the comment below : 
https://github.com/STMicroelectronics/STM32CubeF2/blob/cfa4386ba4eaae35dea33e09bac39b87480345ad/Drivers/STM32F2xx_HAL_Driver/Src/stm32f2xx_hal_iwdg.c#L121-L123
will be updated and made available in future release looks like the following:
```diff
  The timeout value is multiplied by 1000 to be converted in milliseconds.
- LSI startup time is also considered here by adding LSI_STARTUP_TIMEOUT
+ LSI startup time is also considered here by adding LSI_STARTUP_TIME
   converted in milliseconds. 
```
Concerning the define of the LSI_STARTUP_TIME, you can find it in the [include](https://github.com/STMicroelectronics/STM32CubeF2/blob/cfa4386ba4eaae35dea33e09bac39b87480345ad/Drivers/CMSIS/Device/ST/STM32F2xx/Include/stm32f205xx.h) files of the CMSIS device.

Thank you once again for your contribution.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference: 111928

**Comment by TOUNSTM** [comment]
Hello @Kira-sempai,

The fix has been implemented and is now available in the frame of the latest STM32CubeF2 package V1.9.4 release. This issue can be closed now. Thank you again for your contribution.

With Regards,
